### ISSUE TITLE
文件可以通过c$管道正常上传，但是服务开启失败

### ISSUE THREAD

**Issue by UlyssesTakusen** [Amzza0x00/go-impacket#1]
![image](https://user-images.githubusercontent.com/86254141/191161258-7277b694-1c13-4bd2-b5dd-cc6b5bf07fc9.png)

-debug
![image](https://user-images.githubusercontent.com/86254141/191161700-eabff7c7-9dbd-4a0c-8f21-6bf7a7437c18.png)

上传文件没有问题
![image](https://user-images.githubusercontent.com/86254141/191161786-3e903b1e-3d4e-40cb-acfe-b0d2dd2f7d19.png)

**Comment by amzza0x00** [comment]
这个问题貌似是文件名长度导致的，后面我会想办法改一下

**Comment by amzza0x00** [comment]
@UlyssesTakusen 我限制了一下文件名的长度，如果超过11位则会随机生成一个文件名，现在应该没问题了。
